name: assignment9
channels: 
  - conda-forge
  - defaults
dependencies:
  - ipython=7.12.0
  - matplotlib=3.1.3
  - nbconvert=5.6.1
  - numpy=1.18.1
  - python=3.8.1
  - opencv=4.2.0
  - scikit-image=0.16.2
  - scipy=1.4.1
